---
- name: Configure Web Server & Firewall
  hosts: web
  become: yes
  
  vars:
    allowed_subnet: "192.168.1.0/24"

  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Copy Nginx config
      template:
        src: tmpls/nginx.conf.j2
        dest: /etc/nginx/sites-available/default
      notify: Restart Nginx  # <--- Вызов хендлера при изменении

    - name: Deploy Index Page
      template:
        src: tmpls/index.html.j2
        dest: /var/www/html/index.html

    - name: Ensure Nginx is running and enabled
      service:
        name: nginx
        state: started   # <--- Сервис запущен прямо сейчас
        enabled: yes     # <--- Включен в автозапуск (systemd enable)

     - name: Enable UFW Firewall
      ufw:
        state: enabled
        policy: deny  # Явно говорим: всё, что не разрешено — запретить

     - name: Allow SSH
      ufw:
        rule: allow
        name: OpenSSH

     - name: Allow HTTP only from subnet
      ufw:
        rule: allow
        port: '80'
        proto: tcp
        from_ip: "{{ allowed_subnet }}"

   handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
